<form action="/secure/addtodb" method="post">
    <div class="mb-3">
        <h2><label class="form-label" for="inputEmail">Add Role</label></h2>
        <input type="text" class="form-control" id="addrole" name="addrole" placeholder="Add Role">
    </div>





<!-- 
    <div class="mb-3">
        <label class="form-label" for="inputEmail">Products</label>
        <div class="row">
            <div class="col-12">
                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" name="productView" id="productView"  value="pv">
                    
                    <label class="form-check-label" for="productView">Products View</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-check form-check-inline ms-3">
                    <input type="checkbox" class="form-check-input" name="productadd" id="productadd" value="pa" >
                    <label class="form-check-label" for="productadd">Products Add</label>
                </div>

            </div>
        </div>
    </div>

    <div class="mb-3">
        <label class="form-label" for="inputEmail">Orders</label>
        <div class="row">
            <div class="col-12">
                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" name="orderView" id="orderView"  value="ov">
                    
                    <label class="form-check-label" for="orderView">orders View</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-check form-check-inline ms-3">
                    <input type="checkbox" class="form-check-input" name="orderAdd" id="orderAdd" value="oa" >
                    <label class="form-check-label" for="productadd">orders Add</label>
                </div>

            </div>
        </div>
    </div>

    <div class="mb-3">
        <label class="form-label" for="inputEmail">Setting</label>
        <div class="row">
            <div class="col-12">
                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" name="titleOptimization" id="titleOptimization"  value="to1">
                    
                    <label class="form-check-label" for="orderView">title Optimization</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-check form-check-inline ms-3">
                    <input type="checkbox" class="form-check-input" name="Default_Stock" id="Default_Stock" value="ds" >
                    <label class="form-check-label" for="Default_Stock">Default Stock</label>
                </div>

            </div>
            <div class="col-12">
                <div class="form-check form-check-inline ms-3">
                    <input type="checkbox" class="form-check-input" name="Default_Price" id="Default_Price" value="dp" >
                    <label class="form-check-label" for="Default_Price">Default Price</label>
                </div>

            </div>
            <div class="col-12">
                <div class="form-check form-check-inline ms-3">
                    <input type="checkbox" class="form-check-input" name="Default_Zipcode" id="Default_Zipcode" value="dz" >
                    <label class="form-check-label" for="Default_Zipcode">Default zipcode</label>
                </div>

            </div>
        </div>
    </div> -->








    <button type="submit" class="btn btn-primary">Update</button>
</form>