
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>



<head>
  <title>Bootstrap 5 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<?php

echo "<h1>Hello World </h1>";
echo "<h3>Index page </h3>";
echo PHP_EOL;?>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/product/add',
    'Add Product Here!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/product',
    'Product Table Is Here!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/order/add',
    'Orders Add Here!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/order',
    'Order Table Is Here!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/setting',
    'Settings!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/secure/addrole',
    'ADD ROLE!'
);

?>
</div>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/secure/components',
    'ADD COMPONENTS!'
);

?>
</div>
<br><br><br>
<div class="d-inline p-2 bg-light text-white border border-secondary">
<?php echo $this->tag->linkTo(
    '/secure/allowcomponents',
    'ALLOW COMPONENTS!'
);

?>
</div>

